In [12]:
import sys
print('Python Version:\n', sys.version)

import os
result = os.popen('conda list conda').read()
print('\nAnaconda Version:\n', result)

Python Version:
 3.9.18 | packaged by conda-forge | (main, Aug 30 2023, 03:40:31) [MSC v.1929 64 bit (AMD64)]

Anaconda Version:
 # packages in environment at C:\Users\JAVOHIR\miniconda3\envs\mohirdsai:
#
# Name                    Version                   Build  Channel
fonts-conda-ecosystem     1                             0    conda-forge
fonts-conda-forge         1                             0    conda-forge
msys2-conda-epoch         20160418                      1    conda-forge



#### Datasets
- https://www.kaggle.com/rakannimer/air-passengers
- https://www.kaggle.com/lakshmi25npathi/imdb-datasetof
- https://github.com/zalandoresearch/fashion-mnist
- https://jobs.zalando.com/en/tech/
- https://github.com/allisonhorst/palmerpenguins
- https://www.kaggle.com/kingburrito666/shakespeareplays
- https://www.kaggle.com/datasets/uciml/sms-spam-collection-dataset
- https://www.kaggle.com/datasets/ehallmar/a-large-tennis-dataset-for-atp-and-itf-betting
- https://www.openml.org/d/40945
- https://www.kaggle.com/sgus1318/winedata

In [8]:
SetA = set(['Red', 'Blue', 'Green', 'Black'])
SetB = set(['Black', 'Green', 'Yellow', 'Orange'])

In [9]:
SetX = SetA.union(SetB)
SetY = SetA.intersection(SetB)
SetZ = SetA.difference(SetB)

In [23]:
# SetA.issuperset(SetY)

# SetA.issubset(SetX)

# SetA.add('Purple')

# SetA.issubset(SetX)

In [10]:
ListA = [0, 1, 2, 3]
ListB = [4, 5, 6, 7]
ListA.extend(ListB)
ListA

[0, 1, 2, 3, 4, 5, 6, 7]

In [21]:
ListA.append(-5)
ListA

[0, 1, 2, 3, 4, 5, 6, 7, -5, -5]

In [22]:
ListA.remove(-5)
ListA

[0, 1, 2, 3, 4, 5, 6, 7, -5]

In [ ]:
ListX = ListA + ListB

In [ ]:
Letters = [letter.upper() for letter in "Hello"]
print(Letters)

#### Slicing and dicing lists

- MyList.append(x): Adds an element to the end of the list.

- MyList.insert(index, value): Adds an element, value, to the location specified by index to the list.
The first item in a list is numbered 0, rather than 1, as you might think. So,
when adding the number 4 to the front of MyList, you use MyList.
insert(0, 4).

- MyList.remove(x): Removes the first occurrence of x from the list.

- MyList.extend(ListB): Appends the elements in ListB to the end of MyList.

- MyList[a:b]: Returns just the part of the list expressed by the beginning point, a, and the ending point, b. You may optionally add a third element, a step, that tells how  many elements to skip between outputs.

- MyList.index(value): Returns the index of the first occurrence of value in the list.

- MyList.sort(): Sorts the list in order. You may specify reverse=True to sort the list in reverse order. In addition, you can provide a special function to define the sort order.

- len(MyList): Displays the list length.

- max(MyList): Obtains the maximum value in the list.

- min(MyList): Obtains the minimum value in the list.

In [24]:
MyTuple = (1, 2, 3, (4, 5, 6, (7, 8, 9)))

In [25]:
for Value1 in MyTuple:
    if type(Value1) == int:
        print(Value1)
    else:
        for Value2 in Value1:
            if type(Value2) == int:
                print("\t", Value2)
            else:
                for Value3 in Value2:
                    print("\t\t", Value3)

1
2
3
	 4
	 5
	 6
		 7
		 8
		 9


In [26]:
MyNewTuple = MyTuple.__add__((10, 11, 12, (13, 14, 15)))
MyNewTuple

(1, 2, 3, (4, 5, 6, (7, 8, 9)), 10, 11, 12, (13, 14, 15))

In [1]:
def MyLetter():
    for Letter in Letters:
        yield Letter

In [2]:
Letters = [letter.upper() for letter in "Hello"]

In [7]:
ListIt = MyLetter()
next(ListIt)
next(ListIt)
next(ListIt)
next(ListIt)
next(ListIt)

'O'

- https://colab.research.google.com/notebooks/forms.ipynb

In [30]:
import numpy as np

arr1 = np.array([1, 3, 5, 7])
arr2 = np.array([2, 4, 6, 8]).reshape(4, 1)
# dot product of vectors
arr1 @ arr2

array([100])

In [37]:
arr1 ** 2

array([ 1,  9, 25, 49])

In [38]:
2 ** arr1

array([  2,   8,  32, 128], dtype=int32)