# Singular Value Decomposition (SVD)

**SVD equation: $A = U * Σ * V^T$**:
- $A$: An m-x-n matrix that you want to decompose
- $U$: An m-x-m matrix
- $Σ$: An m-x-n diagonal matrix
- $V^T$: A transpose of an n-x-n matrix

In [19]:
import numpy as np

In [20]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(A)

# Perform the decomposition.
U, s, Vt = np.linalg.svd(A)
print("\nU\n", U)
print("\ns\n", s)
print("\nVt\n", Vt)

# Create the m x n Sigma matrix.
Sigma = np.diag(s)
print("\nSigma matrix\n", Sigma)

## You might not have a square matrix, you must specify the size of Sigma
# Sigma = np.zeros((A.shape[0], A.shape[1]))
# Sigma[:A.shape[1], :A.shape[1]] = np.diag(s)

# Reconstruct the original matrix.
B = U.dot(Sigma.dot(Vt))
print("\nReconstructed matrix\n", B)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

U
 [[-0.21483724  0.88723069  0.40824829]
 [-0.52058739  0.24964395 -0.81649658]
 [-0.82633754 -0.38794278  0.40824829]]

s
 [1.68481034e+01 1.06836951e+00 3.33475287e-16]

Vt
 [[-0.47967118 -0.57236779 -0.66506441]
 [-0.77669099 -0.07568647  0.62531805]
 [-0.40824829  0.81649658 -0.40824829]]

Sigma matrix
 [[1.68481034e+01 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 1.06836951e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 3.33475287e-16]]

Reconstructed matrix
 [[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
